// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoRequest.proto

package com.alibaba.dubbo.performance.demo.agent.dubbo.model;

public final class ProtoRequest {
  private ProtoRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.alibaba.dubbo.performance.demo.agent.dubbo.model.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required string methodName = 2;</code>
     */
    boolean hasMethodName();
    /**
     * <code>required string methodName = 2;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>required string methodName = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>required string interfaceNama = 3;</code>
     */
    boolean hasInterfaceNama();
    /**
     * <code>required string interfaceNama = 3;</code>
     */
    java.lang.String getInterfaceNama();
    /**
     * <code>required string interfaceNama = 3;</code>
     */
    com.google.protobuf.ByteString
        getInterfaceNamaBytes();

    /**
     * <code>required string parameterTypes = 4;</code>
     */
    boolean hasParameterTypes();
    /**
     * <code>required string parameterTypes = 4;</code>
     */
    java.lang.String getParameterTypes();
    /**
     * <code>required string parameterTypes = 4;</code>
     */
    com.google.protobuf.ByteString
        getParameterTypesBytes();

    /**
     * <code>required string arguments = 5;</code>
     */
    boolean hasArguments();
    /**
     * <code>required string arguments = 5;</code>
     */
    java.lang.String getArguments();
    /**
     * <code>required string arguments = 5;</code>
     */
    com.google.protobuf.ByteString
        getArgumentsBytes();
  }
  /**
   * Protobuf type {@code com.alibaba.dubbo.performance.demo.agent.dubbo.model.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.alibaba.dubbo.performance.demo.agent.dubbo.model.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      id_ = 0L;
      methodName_ = "";
      interfaceNama_ = "";
      parameterTypes_ = "";
      arguments_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              methodName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              interfaceNama_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              parameterTypes_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              arguments_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.internal_static_com_alibaba_dubbo_performance_demo_agent_dubbo_model_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.internal_static_com_alibaba_dubbo_performance_demo_agent_dubbo_model_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request.class, com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int METHODNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object methodName_;
    /**
     * <code>required string methodName = 2;</code>
     */
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string methodName = 2;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          methodName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string methodName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERFACENAMA_FIELD_NUMBER = 3;
    private volatile java.lang.Object interfaceNama_;
    /**
     * <code>required string interfaceNama = 3;</code>
     */
    public boolean hasInterfaceNama() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string interfaceNama = 3;</code>
     */
    public java.lang.String getInterfaceNama() {
      java.lang.Object ref = interfaceNama_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          interfaceNama_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string interfaceNama = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInterfaceNamaBytes() {
      java.lang.Object ref = interfaceNama_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interfaceNama_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMETERTYPES_FIELD_NUMBER = 4;
    private volatile java.lang.Object parameterTypes_;
    /**
     * <code>required string parameterTypes = 4;</code>
     */
    public boolean hasParameterTypes() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string parameterTypes = 4;</code>
     */
    public java.lang.String getParameterTypes() {
      java.lang.Object ref = parameterTypes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          parameterTypes_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string parameterTypes = 4;</code>
     */
    public com.google.protobuf.ByteString
        getParameterTypesBytes() {
      java.lang.Object ref = parameterTypes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parameterTypes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARGUMENTS_FIELD_NUMBER = 5;
    private volatile java.lang.Object arguments_;
    /**
     * <code>required string arguments = 5;</code>
     */
    public boolean hasArguments() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string arguments = 5;</code>
     */
    public java.lang.String getArguments() {
      java.lang.Object ref = arguments_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          arguments_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string arguments = 5;</code>
     */
    public com.google.protobuf.ByteString
        getArgumentsBytes() {
      java.lang.Object ref = arguments_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arguments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInterfaceNama()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParameterTypes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArguments()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, interfaceNama_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, parameterTypes_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, arguments_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, methodName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, interfaceNama_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, parameterTypes_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, arguments_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request)) {
        return super.equals(obj);
      }
      com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request other = (com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasMethodName() == other.hasMethodName());
      if (hasMethodName()) {
        result = result && getMethodName()
            .equals(other.getMethodName());
      }
      result = result && (hasInterfaceNama() == other.hasInterfaceNama());
      if (hasInterfaceNama()) {
        result = result && getInterfaceNama()
            .equals(other.getInterfaceNama());
      }
      result = result && (hasParameterTypes() == other.hasParameterTypes());
      if (hasParameterTypes()) {
        result = result && getParameterTypes()
            .equals(other.getParameterTypes());
      }
      result = result && (hasArguments() == other.hasArguments());
      if (hasArguments()) {
        result = result && getArguments()
            .equals(other.getArguments());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasMethodName()) {
        hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
        hash = (53 * hash) + getMethodName().hashCode();
      }
      if (hasInterfaceNama()) {
        hash = (37 * hash) + INTERFACENAMA_FIELD_NUMBER;
        hash = (53 * hash) + getInterfaceNama().hashCode();
      }
      if (hasParameterTypes()) {
        hash = (37 * hash) + PARAMETERTYPES_FIELD_NUMBER;
        hash = (53 * hash) + getParameterTypes().hashCode();
      }
      if (hasArguments()) {
        hash = (37 * hash) + ARGUMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getArguments().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.alibaba.dubbo.performance.demo.agent.dubbo.model.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.alibaba.dubbo.performance.demo.agent.dubbo.model.Request)
        com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.internal_static_com_alibaba_dubbo_performance_demo_agent_dubbo_model_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.internal_static_com_alibaba_dubbo_performance_demo_agent_dubbo_model_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request.class, com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request.Builder.class);
      }

      // Construct using com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        interfaceNama_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        parameterTypes_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        arguments_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.internal_static_com_alibaba_dubbo_performance_demo_agent_dubbo_model_Request_descriptor;
      }

      public com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request getDefaultInstanceForType() {
        return com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request.getDefaultInstance();
      }

      public com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request build() {
        com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request buildPartial() {
        com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request result = new com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.interfaceNama_ = interfaceNama_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.parameterTypes_ = parameterTypes_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.arguments_ = arguments_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request) {
          return mergeFrom((com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request other) {
        if (other == com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasMethodName()) {
          bitField0_ |= 0x00000002;
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.hasInterfaceNama()) {
          bitField0_ |= 0x00000004;
          interfaceNama_ = other.interfaceNama_;
          onChanged();
        }
        if (other.hasParameterTypes()) {
          bitField0_ |= 0x00000008;
          parameterTypes_ = other.parameterTypes_;
          onChanged();
        }
        if (other.hasArguments()) {
          bitField0_ |= 0x00000010;
          arguments_ = other.arguments_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasMethodName()) {
          return false;
        }
        if (!hasInterfaceNama()) {
          return false;
        }
        if (!hasParameterTypes()) {
          return false;
        }
        if (!hasArguments()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>required string methodName = 2;</code>
       */
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            methodName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object interfaceNama_ = "";
      /**
       * <code>required string interfaceNama = 3;</code>
       */
      public boolean hasInterfaceNama() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string interfaceNama = 3;</code>
       */
      public java.lang.String getInterfaceNama() {
        java.lang.Object ref = interfaceNama_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            interfaceNama_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string interfaceNama = 3;</code>
       */
      public com.google.protobuf.ByteString
          getInterfaceNamaBytes() {
        java.lang.Object ref = interfaceNama_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          interfaceNama_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string interfaceNama = 3;</code>
       */
      public Builder setInterfaceNama(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        interfaceNama_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string interfaceNama = 3;</code>
       */
      public Builder clearInterfaceNama() {
        bitField0_ = (bitField0_ & ~0x00000004);
        interfaceNama_ = getDefaultInstance().getInterfaceNama();
        onChanged();
        return this;
      }
      /**
       * <code>required string interfaceNama = 3;</code>
       */
      public Builder setInterfaceNamaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        interfaceNama_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object parameterTypes_ = "";
      /**
       * <code>required string parameterTypes = 4;</code>
       */
      public boolean hasParameterTypes() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string parameterTypes = 4;</code>
       */
      public java.lang.String getParameterTypes() {
        java.lang.Object ref = parameterTypes_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            parameterTypes_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string parameterTypes = 4;</code>
       */
      public com.google.protobuf.ByteString
          getParameterTypesBytes() {
        java.lang.Object ref = parameterTypes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parameterTypes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string parameterTypes = 4;</code>
       */
      public Builder setParameterTypes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        parameterTypes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string parameterTypes = 4;</code>
       */
      public Builder clearParameterTypes() {
        bitField0_ = (bitField0_ & ~0x00000008);
        parameterTypes_ = getDefaultInstance().getParameterTypes();
        onChanged();
        return this;
      }
      /**
       * <code>required string parameterTypes = 4;</code>
       */
      public Builder setParameterTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        parameterTypes_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object arguments_ = "";
      /**
       * <code>required string arguments = 5;</code>
       */
      public boolean hasArguments() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string arguments = 5;</code>
       */
      public java.lang.String getArguments() {
        java.lang.Object ref = arguments_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            arguments_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string arguments = 5;</code>
       */
      public com.google.protobuf.ByteString
          getArgumentsBytes() {
        java.lang.Object ref = arguments_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          arguments_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string arguments = 5;</code>
       */
      public Builder setArguments(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        arguments_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string arguments = 5;</code>
       */
      public Builder clearArguments() {
        bitField0_ = (bitField0_ & ~0x00000010);
        arguments_ = getDefaultInstance().getArguments();
        onChanged();
        return this;
      }
      /**
       * <code>required string arguments = 5;</code>
       */
      public Builder setArgumentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        arguments_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.alibaba.dubbo.performance.demo.agent.dubbo.model.Request)
    }

    // @@protoc_insertion_point(class_scope:com.alibaba.dubbo.performance.demo.agent.dubbo.model.Request)
    private static final com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request();
    }

    public static com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.alibaba.dubbo.performance.demo.agent.dubbo.model.ProtoRequest.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_dubbo_performance_demo_agent_dubbo_model_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alibaba_dubbo_performance_demo_agent_dubbo_model_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ProtoRequest.proto\0224com.alibaba.dubbo." +
      "performance.demo.agent.dubbo.model\"k\n\007Re" +
      "quest\022\n\n\002id\030\001 \002(\003\022\022\n\nmethodName\030\002 \002(\t\022\025\n" +
      "\rinterfaceNama\030\003 \002(\t\022\026\n\016parameterTypes\030\004" +
      " \002(\t\022\021\n\targuments\030\005 \002(\tBD\n4com.alibaba.d" +
      "ubbo.performance.demo.agent.dubbo.modelB" +
      "\014ProtoRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_alibaba_dubbo_performance_demo_agent_dubbo_model_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alibaba_dubbo_performance_demo_agent_dubbo_model_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alibaba_dubbo_performance_demo_agent_dubbo_model_Request_descriptor,
        new java.lang.String[] { "Id", "MethodName", "InterfaceNama", "ParameterTypes", "Arguments", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
